version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: "unless-stopped"
    # Port 8096 (web)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${USED_DOCKER_DATA}/jellyfin/config:/config
      - ${USED_DOCKER_DATA}/jellyfin/cache:/cache
      - ${USED_MEDIA_PATH}/Shows:/data/tvshows
      - ${USED_MEDIA_PATH}/Movies:/data/movies
      - ${USED_MEDIA_PATH}/Porn:/data/porn
      - ${USED_MEDIA_PATH}/Temp:/data/temp
      - ${USED_MEDIA_PATH}/Music:/data/music

  #jellyseerr:
  #  image: fallenbagel/jellyseerr:latest
  #  container_name: jellyseerr
  #  restart: unless-stopped
  #  # Port 5055 (web)
  #  environment:
  #    - LOG_LEVEL=debug
  #    - TZ=Europe/Zurich
  #  volumes:
  #    - ${USED_DOCKER_DATA}/jellyseerr/config:/app/config

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${USED_DOCKER_DATA}/deluge/config:/config
      - ${USED_DOWNLOADS_PATH}/Downloading:/downloads
    # Port 8112 (web)
    ports:
      - 6881:6881 # Port 6881 (torrent)
      - 6881:6881/udp # Port 6881 (torrent)

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${USED_DOCKER_DATA}/prowlarr/config:/config
    # Port 9696 (web)

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${USED_DOCKER_DATA}/sonarr/config:/config
      - ${USED_DOWNLOADS_PATH}/Downloading:/downloads
      - ${USED_MEDIA_PATH}/Shows:/tv
    # Port 8989 (web)

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${USED_DOCKER_DATA}/radarr/config:/config
      - ${USED_DOWNLOADS_PATH}/Downloading:/downloads
      - ${USED_MEDIA_PATH}/Movies:/movies
    # Port 7878 (web)
networks:
  default:
    name: nginx_default
    external: true