#!/bin/bash

PATH_TO_SERVER_LOCATION = $HOME/truenas
PATH_TO_SCRIPTS = "$HOME/bash-debian-server"

PATH_TO_SERVER_CONFIG = $PATH_TO_SERVER_LOCATION/Config

PATH_TO_SERVER_CONFIG_DATA = $PATH_TO_SERVER_LOCATION/Config/server_data

PATH_TO_SERVER_PUBLIC = $PATH_TO_SERVER_LOCATION/Public
PATH_TO_SERVER_MEDIA = $PATH_TO_SERVER_PUBLIC/Torrent

PATH_TO_JELLYFIN = $HOME/jellyfin
PATH_TO_JELLYFIN_CONFIG = $PATH_TO_JELLYFIN/jellyfin_config
PATH_TO_JELLYFIN_CACHE = $PATH_TO_JELLYFIN/jellyfin_cache